### ISSUE TITLE
react-native-web

### ISSUE THREAD

**Issue by Hermanya** [vincentriemer/react-native-dom#17]
Hello, I'm trying to understand the difference between this project and https://necolas.github.io/react-native-web/storybook/. It would be useful, to have an explanation in the readme.

**Comment by idibidiart** [comment]
For one thing, Yoga, RN's layout engine, is ported to WASM in this project. Not so in RN Web. The advantage is that you get identical layout behavior, guaranteed. 

Another thing that is an advantage here is all component logic runs in a worker thread, allowing the UI thread to be exclusively used for rendering.

And I believe this uses Custom Elements, part of the Web Components spec.

And the same build system/packager as RN. 

Correct me if I'm wrong.

**Comment by motiz88** [comment]
Seems like the intro to the README sums it up nicely, only without mentioning `react-native-web` specifically:

> Multithreaded by default
> Same layout behavior as React Native on mobile
> Built with the same bundler used for existing React Native platforms
> Ecosystem compatible escape hatch to the DOM

These are pretty much the main differences between this project and `react-native-web`. That, and being newer and more experimental.

**Comment by slorber** [comment]
ReactNativeWeb has a babel plugin which replaces all `import { View } from "react-native"` by `import { View } from "react-native-web"`

And the View from ReactNativeWeb is just some custom component with styles and behaviors trying to match the native RN platform components.

For instance, as you know the RN views are by default flex based with column direction, so a simple RNW View implementation could be:

```js
const View = ({style, ...props}) => <div style={{display: "flex", flexDirection: "column", ...style}} {...props}/>
```

So, as you understand, the View element is actually just a regular component, there is no special magic.

With RNW, it's totally working to mix RN components with regular DOM nodes. Obviously this would only work on web platform. This looks weird but you could write:

```js
const MyComp = () => (
  <div>
    <View>
      <a href="https//ssd"><Text>link</Text></a>
    </View> 
  </div>
);
```

On the contrary, this project is taking a different approach. Instead of providing custom dom components to replace the RN components at build time (thanks to RNW babel plugin), you actually use the real RN components themselves, and the RN platform now targets the DOM the same way it supports Android and iOS:
- it has background thread for React rendering in WebWorker
- it has a background<->UI bridge to send diff update operations to the UI
- it has a UI thread for dom operations, that you cannot access directly from your React component code


By using the same architecture than on mobile and adding more constraints (ie running in a webworker, unability to mix RN and dom nodes, communication to UI with a bridge, using same layout engine...), we get a system that is much closer to the existing RN mobile apps. 

The View of RND is on the native side (UI) and your components on the background side (WebWorker), while the View of RNW is just a custom element on the UI side, and your components are also on the UI side, calling the View components as any regular custom components.

**Comment by Nkzn** [comment]
I recognize the difference as shown in the figure below.

![difference-rnd-rnw](https://user-images.githubusercontent.com/434227/40578134-cdfcc274-6149-11e8-8079-8c355ce5451f.png)
