### ISSUE TITLE
Hard time understanding the use case for this

### ISSUE THREAD

**Issue by abacaj** [vincentriemer/react-native-dom#27]
Maybe I'm a bit behind in web trends and totally missing the point, I have a few questions someone may be able to answer.

Q1. What is the point of a mobile framework being ported to web?
Q2. Why aren't we just optimizing react.js for the web?
Q3. It feels like we are confusing the frontend landscape with even more frameworks, like my previous question - why not just contribute to react.js...
Q4. Don't we have electron + react.js for web to native desktop experience? What is the purpose of this?

**Comment by kripken** [comment]
I believe another use case (also mentioned and demoed in the talk) is if you happen to have an existing React Native app already, this project gives you an easy way to run it on the web with the exact same layout and so forth.

**Comment by jhohlfeld** [comment]
@abacai I must respond to your points, because I strongly feel for rapid evolutionary development in all areas, especially software.

There’s not much to gain in asking „why do we need this“ or „wouldn’t it just make sense to instead keep X“? Somewhere somebody will find this useful and interesting and good ideas will always prevail. You simply don’t know what this particular idea or strain of development will be. I have one plea: keep your mind open. If it doesn’t suit your needs, it sure will suit somebody else‘s.

**Comment by jhohlfeld** [comment]
By the way narrowing the gap in terms of layout between mobile and web would be a huge win. Does anybody have experience how the javascript-driven layouting performs compared to DOM done by the browser? I assume there will be some major perf issues lurking, right?

**Comment by slorber** [comment]
Note that big players like Twitter, AirBnB and MLS are already using stuff like react-native-web and react-primitive in productions, and they share their React components across platforms (React, RN, VR, Sketch...) with great success. You can also check this issue about the differences between currently used solutions to achieve that and this new solution [here](https://github.com/vincentriemer/react-native-dom/issues/17).

**Comment by peacechen** [comment]
It's great that they've been able to get react-native-web working for their projects.  But they use it because that was the only solution available, not because it works so well.  It does an admirable job trying to map RN components to their DOM equivalents, but there's a ton of infrastructure missing.  The key point that you made is that the've used pieces of their app with react-native-web, not the whole app.

`react-native-dom` OTOH has the potential to run the *entire* app as-is in the browser.
Platform differences will always arise (e.g. Android vs iOS in RN). Each platform needs some small amount of accommodation, but the overall app infrastructure is retained.

**Comment by motiz88** [comment]
Some good answers in this thread (thanks everyone) - Closing this as the README already links to the talk for the overall "why?" and we have #17 for more focused discussion of RNDom vs RNWeb.
